### ISSUE TITLE
Quelle système de présentation ?

### ISSUE THREAD

**Issue by Plou** [Inouit/t3uni14-presentation#1]
Quoi utiliser pour la présentation ?
- [revealjs](http://lab.hakim.se/reveal-js/) (utilisé pour la présentation sur yeoman / dummy)
  - Testé et maîtrisé
- [IO-Slides](https://github.com/NicolasRitouet/generator-io-slides) (google)
  - Le thème est plus sobre et joli, quelques fonctionnalisées en plus
- Keynote / Powerpoint (T_T)

**Comment by Gregcop1** [comment]
je pensais bien à reveal, mais il faut que je vois avec la t3uni s'ils ont
un format et un skin de présentation (une année, ils avaient fait ça)

2014-02-20 11:25 GMT+01:00 Plou notifications@github.com:

**Comment by Plou** [comment]
RevealJS car déjà prêt (generator-reveal)
