### ISSUE TITLE
Le générateur de contenu préformatés

### ISSUE THREAD

**Issue by Plou** [Inouit/t3uni14-presentation#6]

**Comment by Plou** [comment]
Cette section nécessiterai une présentation rapide de WEC Content Element.

**Comment by Gregcop1** [comment]
Oui et non en fait. Oui pour dire vite fait à quoi ça sert et que ça
combine Ts, locallang, etc
mais en mm temps, je pense qu'on va bientôt se tourner vers gridelement qui
est en passe de devenir LE truc officiel. Je n'ai pas encore regardé mais
si nous ne nous y sommes pas mis d'ici là, il faudra simplement dire qu'on
peut envisager la mm chose avec gridelement

2014-03-03 11:46 GMT+01:00 Plou notifications@github.com:
